app:
  auth:
    success-login-redirect-url: ${SUCCESS_LOGIN_REDIRECT}
    post-logout-redirect-url: ${POST_LOGOUT_REDIRECT_URL}
  gateway:
    client-id: ${GATEWAY_CLIENT_ID}
    client-secret: ${GATEWAY_CLIENT_SECRET}
  adapters:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: ${CORS_ALLOWED_METHODS}
      allowed-headers: ${CORS_ALLOWED_HEADERS}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS}
      max-age: ${CORS_MAX_AGE_SECONDS}

server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true

  application:
    name: api-gateway

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}

  session:
    timeout: ${SESSION_DURATION}
    data:
      redis:
        namespace: simple-wms:session

  security:
    oauth2:
      client:
        registration:
          simple-wms-api-gateway: # ${GATEWAY_CLIENT_ID} this placeholder does not work there - don't try to
            provider: simple-wms-auth
            client-id: ${GATEWAY_CLIENT_ID}
            client-secret: ${GATEWAY_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - wms:all
        provider:
          simple-wms-auth:
            issuer-uri: ${AUTH_SERVER_ISSUER_URL} # if setted up then makes get .wellknowns and get the configuration
                                                  # and endpoints from auth-service and as i understood settings below override configs from auth-service

            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            jwk-set-uri: ${JWK_SET_URI}
            user-info-uri: ${USER_INFO_URI}
            user-name-attribute: sub

  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      server:
        webmvc:
          routes:
            # ========== Business Routes ==========
            - id: receiving-service
              uri: http://receiving-service:8080
              predicates:
                - Path=/api/receiving-service/**
              filters:
                - TokenRelay=

            - id: user-service
              uri: http://auth-service:9000
              predicates:
                - Path=/api/users/**
              filters:
                - TokenRelay=

            # ========== OpenAPI spec ==========
            - id: auth-service-docs
              uri: http://auth-service:9000
              predicates:
                - Path=/v3/api-docs/auth-service/**

            - id: receiving-service-docs
              uri: http://receiving-service:8080
              predicates:
                - Path=/v3/api-docs/receiving-service/**


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth-service
      - name: Receiving Service
        url: /v3/api-docs/receiving-service
      - name: Gateway API
        url: /v3/api-docs
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    org.springframework.boot.actuate: WARN